### ISSUE TITLE
Adicionar resumo do sistema

### ISSUE THREAD

**Issue by dijalmasilva** [ads-ifpb-praticas-20161/socialsportsbrasil#1]
Criar um resumo do sistema afim de especificar detalhadamente os requisitos do mesmo.

**Comment by dijalmasilva** [comment]
Leia o documento escrito no Wiki e escreva funcionalidades que você acha que o sistema pode ter.
Aí depois é só adicionar como a funcionalidade deve funcionar detalhadamente.

@asheleyemmy

**Comment by joseferreir** [comment]
veja o que esta pendente e faça a inserção.  
@dijalmasilva @asheleyemmy
